# 1. Import libraries

In [1]:
import sys
from pathlib import Path
from tqdm import tqdm

# scientific
import pandas as pd
import numpy as np

# bio
import gffutils

# custom
sys.path.append(str(Path.cwd().parent / "src"))
from utils import update_sysIDs
from enrichment_functions import OntologyDataConfig, load_ontology_data
from pombe_feature_functions import config, DNA_level_features, extract_protein_features_from_peptide_sequence
from protein_structure_functions import pLDDT_statistics_report

# 2. Constants

In [59]:
ALPHAFOLD_DATABASE_DIR = Path("../../../resource/AlphaFold_Dataset/20251107_downloaded/UP000002485_284812_SCHPO_v6")

OUTPUT_DIR = Path("../../resources/pombe_features")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 3. Configurations

In [3]:
cfg = config()
db = gffutils.create_db(cfg.gff3_file, cfg.database_file, force=True)
db = gffutils.FeatureDB(cfg.database_file)

In [4]:
gene_meta = pd.read_csv(cfg.gene_meta_file, sep="\t")
uniprot2id = dict(zip(gene_meta["uniprot_id"], gene_meta["gene_systematic_id"]))

# 4. Collect features

## 4.1 DNA-level features

In [5]:
mRNAs = list(db.features_of_type('mRNA'))
coding_gene_DNA_features = []

for ix, mRNA in enumerate(mRNAs):
    gene_DNA_features = DNA_level_features.from_gffutils_feature(mRNA, db, cfg)
    coding_gene_DNA_features.append(gene_DNA_features)

coding_gene_DNA_features_df = pd.DataFrame(coding_gene_DNA_features)
coding_genes = coding_gene_DNA_features_df['Gene_id'].unique().tolist()

/data/a/yangyusheng/miniforge3/envs/bioinformatics/lib/python3.12/site-packages/Bio/Seq.py:2879: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
/data/a/yangyusheng/miniforge3/envs/bioinformatics/lib/python3.12/site-packages/Bio/Seq.py:2879: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(

In [6]:
coding_gene_DNA_features_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5145 entries, 0 to 5144
Data columns (total 27 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gene_id                            5145 non-null   object
 1   mRNA_id                            5145 non-null   object
 2   Chromosome                         5145 non-null   object
 3   Start                              5145 non-null   int64
 4   End                                5145 non-null   int64
 5   Strand                             5145 non-null   object
 6   Abs_distance_from_telomere         5127 non-null   float64
 7   Relative_distance_from_telomere    5127 non-null   float64
 8   Abs_distance_from_centromere       5127 non-null   float64
 9   Relative_distance_from_centromere  5127 non-null   float64
 10  Gene_length                        5145 non-null   int64
 11  GC_content_of_gene                 5145 non-null   float64
 12  CDS_number                         5145 non-null   int64
 13  GC_content_of_CDS                  5145 non-null   float64
 14  Fraction_of_CDS                    5145 non-null   float64
 15  GC3                                5145 non-null   float64
 16  Containing_intron                  5145 non-null   bool
 17  Intron_number                      5145 non-null   int64
 18  GC_content_of_intron               5145 non-null   float64
 19  Total_intron_length                5145 non-null   int64
 20  Average_intron_length              5145 non-null   float64
 21  Length_of_first_intron             5145 non-null   int64
 22  GC_contents_of_first_intron        5145 non-null   float64
 23  ENC                                5145 non-null   float64
 24  Peptide_length                     5145 non-null   int64
 25  Primary_peptide_length             5145 non-null   int64
 26  Primary_candidate                  5145 non-null   bool
dtypes: bool(2), float64(12), int64(9), object(4)
memory usage: 1015.1+ KB

In [7]:
coding_gene_DNA_features_df.head()

,Gene_id,mRNA_id,Chromosome,Start,End,Strand,Abs_distance_from_telomere,Relative_distance_from_telomere,Abs_distance_from_centromere,Relative_distance_from_centromere,...,Intron_number,GC_content_of_intron,Total_intron_length,Average_intron_length,Length_of_first_intron,GC_contents_of_first_intron,ENC,Peptide_length,Primary_peptide_length,Primary_candidate
0,SPAC1002.01,SPAC1002.01.1,I,1798347,1798835,+,1768928.0,0.317,1972963.0,0.354,...,0,0.0,0,0.0,0,0.0,51.38,162,162,True
1,SPAC1002.02,SPAC1002.02.1,I,1799128,1799817,+,1769809.0,0.317,1972082.0,0.353,...,0,0.0,0,0.0,0,0.0,51.30,229,229,True
2,SPAC1002.03c,SPAC1002.03c.1,I,1802983,1800212,-,1771934.0,0.318,1969957.0,0.353,...,0,0.0,0,0.0,0,0.0,46.99,923,923,True
3,SPAC1002.04c,SPAC1002.04c.1,I,1804372,1803773,-,1774409.0,0.318,1967482.0,0.353,...,0,0.0,0,0.0,0,0.0,48.62,199,199,True
4,SPAC1002.05c,SPAC1002.05c.1,I,1806797,1804650,-,1776060.0,0.318,1965831.0,0.352,...,0,0.0,0,0.0,0,0.0,51.95,715,715,True

In [8]:
coding_gene_DNA_features_df.describe()

,Start,End,Abs_distance_from_telomere,Relative_distance_from_telomere,Abs_distance_from_centromere,Relative_distance_from_centromere,Gene_length,GC_content_of_gene,CDS_number,GC_content_of_CDS,...,GC3,Intron_number,GC_content_of_intron,Total_intron_length,Average_intron_length,Length_of_first_intron,GC_contents_of_first_intron,ENC,Peptide_length,Primary_peptide_length
count,5.145000e+03,5.145000e+03,5.127000e+03,5127.000000,5.127000e+03,5127.000000,5145.00000,5145.000000,5145.000000,5145.000000,...,5145.000000,5145.000000,5145.000000,5145.000000,5145.000000,5145.000000,5145.000000,5145.000000,5145.000000,5145.000000
mean,2.321891e+06,2.321875e+06,1.150535e+06,0.247395,1.266849e+06,0.270864,1478.04898,0.391836,1.992031,0.399018,...,33.644190,1.019242,0.138958,85.548882,45.422819,44.907677,0.138441,49.168389,464.204665,464.540330
std,1.468431e+06,1.468427e+06,7.379389e+05,0.141984,9.200347e+05,0.173888,1112.29617,0.035507,1.485196,0.034730,...,5.223697,1.497607,0.148781,135.824531,80.349827,83.658884,0.150507,2.825395,371.287835,371.177668
min,6.930000e+02,1.000000e+00,1.790000e+02,0.000000,1.960700e+04,0.004000,87.00000,0.192000,1.000000,0.190000,...,5.263000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32.850000,21.000000,24.000000
25%,1.094653e+06,1.094045e+06,5.287575e+05,0.125000,5.336032e+05,0.125500,762.00000,0.369000,1.000000,0.377000,...,30.537000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,48.150000,223.000000,224.000000
50%,2.138363e+06,2.139127e+06,1.051947e+06,0.249000,1.058274e+06,0.249000,1220.00000,0.388000,1.000000,0.396000,...,32.731000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,49.610000,378.000000,378.000000
75%,3.494183e+06,3.493092e+06,1.739156e+06,0.369000,1.797746e+06,0.397000,1842.00000,0.411000,3.000000,0.417000,...,35.581000,2.000000,0.289000,133.000000,64.000000,58.000000,0.288000,50.930000,583.000000,583.000000
max,5.579133e+06,5.578447e+06,2.762371e+06,0.495000,3.768723e+06,0.676000,15005.00000,0.550000,16.000000,0.549000,...,65.738000,15.000000,1.000000,2526.000000,2526.000000,2526.000000,1.000000,57.250000,4924.000000,4924.000000

## 4.2 RNA-level features

### RNA abundance

In [80]:
mRNA_abundance = pd.read_excel("../../resources/Literature/PMID23101633/mmc1.xlsx", sheet_name="Table_S2", comment="#").set_index('Systematic.name')
mRNA_abundance = mRNA_abundance[['MM1.tot.cpc_ex', 'MM2.tot.cpc_ex', 'MN1.tot.cpc_ex', 'MN2.tot.cpc_ex']].copy()
mRNA_abundance.columns = pd.MultiIndex.from_tuples([("EMM_Proliferating_Cell_RNA_Abundance", "replicate1"), ("EMM_Proliferating_Cell_RNA_Abundance", "replicate2"), ("EMM_Nitrogen_Starved_Cell_RNA_Abundance", "replicate1"), ("EMM_Nitrogen_Starved_Cell_RNA_Abundance", "replicate2")], name=["Condition", "Replicate"])
mean_mRNA_abundance = mRNA_abundance.T.groupby(level="Condition").mean().T
std_mRNA_abundance = mRNA_abundance.T.groupby(level="Condition").std().T
cv_mRNA_abundance = std_mRNA_abundance / mean_mRNA_abundance
mRNA_abundance_statistics = pd.concat([mean_mRNA_abundance, std_mRNA_abundance, cv_mRNA_abundance], axis=1, keys=['mean', 'std', 'cv'])
mRNA_abundance_statistics.index = update_sysIDs(mRNA_abundance_statistics.index.tolist(), cfg.gene_meta_file)
coding_gene_mRNA_abundace_statistics = mRNA_abundance_statistics[mRNA_abundance_statistics.index.isin(coding_genes)].copy().dropna().round(3)
coding_gene_mRNA_abundace_statistics.columns = ["_".join(col).strip() for col in coding_gene_mRNA_abundace_statistics.columns.values]
coding_gene_mRNA_abundace_statistics = coding_gene_mRNA_abundace_statistics[coding_gene_mRNA_abundace_statistics.index.isin(coding_genes)].copy()
coding_gene_mRNA_abundace_statistics = coding_gene_mRNA_abundace_statistics.rename_axis("gene_systematic_id").reset_index().drop_duplicates(subset=["gene_systematic_id"]).set_index("gene_systematic_id")

SPAC212.10 is not found in geneid2symbol or synonyms2ID
SPAC212.09c is not found in geneid2symbol or synonyms2ID
SPNCRNA.70 is not found in geneid2symbol or synonyms2ID
SPAC212.07c is not found in geneid2symbol or synonyms2ID
SPAC212.05c is not found in geneid2symbol or synonyms2ID
LTR.21035 is not found in geneid2symbol or synonyms2ID
LTR.24281 is not found in geneid2symbol or synonyms2ID
LTR.24581 is not found in geneid2symbol or synonyms2ID
LTR.25997 is not found in geneid2symbol or synonyms2ID
LTR.28124 is not found in geneid2symbol or synonyms2ID
LTR.32863 is not found in geneid2symbol or synonyms2ID
SPNCRNA.136 is not found in geneid2symbol or synonyms2ID
SPNCRNA.601 is not found in geneid2symbol or synonyms2ID
SPNCRNA.602 is not found in geneid2symbol or synonyms2ID
SPNCRNA.19 is not found in geneid2symbol or synonyms2ID
LTR.54499 is not found in geneid2symbol or synonyms2ID
SPAC977.13c is not found in geneid2symbol or synonyms2ID
SPNCRNA.137 is not found in geneid2symbol or synonyms2ID
SPNCRNA.37 is not found in geneid2symbol or synonyms2ID
SPNCRNA.83 is not found in geneid2symbol or synonyms2ID
LTR.73709 is not found in geneid2symbol or synonyms2ID
LTR.73945 is not found in geneid2symbol or synonyms2ID
SPNCRNA.138 is not found in geneid2symbol or synonyms2ID
SPNCRNA.76 is not found in geneid2symbol or synonyms2ID
LTR.79680 is not found in geneid2symbol or synonyms2ID
SPNCRNA.603 is not found in geneid2symbol or synonyms2ID
SPNCRNA.604 is not found in geneid2symbol or synonyms2ID
SPNCRNA.139 is not found in geneid2symbol or synonyms2ID
SPNCRNA.605 is not found in geneid2symbol or synonyms2ID
SPNCRNA.606 is not found in geneid2symbol or synonyms2ID
LTR.98631 is not found in geneid2symbol or synonyms2ID
LTR.98988 is not found in geneid2symbol or synonyms2ID
SPNCRNA.607 is not found in geneid2symbol or synonyms2ID
LTR.106349 is not found in geneid2symbol or synonyms2ID
SPNCRNA.608 is not found in geneid2symbol or synonyms2ID
SPNCRNA.609 is not found in geneid2symbol or synonyms2ID
SPNCRNA.147 is not found in geneid2symbol or synonyms2ID
SPNCRNA.610 is not found in geneid2symbol or synonyms2ID
SPNCRNA.611 is not found in geneid2symbol or synonyms2ID
SPNCRNA.612 is not found in geneid2symbol or synonyms2ID
SPNCRNA.613 is not found in geneid2symbol or synonyms2ID
SPRRNA.10 is not found in geneid2symbol or synonyms2ID
SPNCRNA.614 is not found in geneid2symbol or synonyms2ID
SPNCRNA.615 is not found in geneid2symbol or synonyms2ID
SPNCRNA.616 is not found in geneid2symbol or synonyms2ID
SPNCRNA.617 is not found in geneid2symbol or synonyms2ID
SPSNORNA.49 is not found in geneid2symbol or synonyms2ID
SPNCRNA.141 is not found in geneid2symbol or synonyms2ID
SPNCRNA.618 is not found in geneid2symbol or synonyms2ID
SPNCRNA.619 is not found in geneid2symbol or synonyms2ID
SPNCRNA.620 is not found in geneid2symbol or synonyms2ID
SPNCRNA.621 is not found in geneid2symbol or synonyms2ID
SPNCRNA.622 is not found in geneid2symbol or synonyms2ID
SPNCRNA.623 is not found in geneid2symbol or synonyms2ID
SPNCRNA.142 is not found in geneid2symbol or synonyms2ID
SPNCRNA.624 is not found in geneid2symbol or synonyms2ID
SPNCRNA.625 is not found in geneid2symbol or synonyms2ID
SPNCRNA.143 is not found in geneid2symbol or synonyms2ID
SPNCRNA.03 is not found in geneid2symbol or synonyms2ID
SPNCRNA.626 is not found in geneid2symbol or synonyms2ID
SPNCRNA.627 is not found in geneid2symbol or synonyms2ID
SPNCRNA.144 is not found in geneid2symbol or synonyms2ID
SPNCRNA.628 is not found in geneid2symbol or synonyms2ID
SPNCRNA.145 is not found in geneid2symbol or synonyms2ID
SPNCRNA.629 is not found in geneid2symbol or synonyms2ID
SPNCRNA.630 is not found in geneid2symbol or synonyms2ID
SPNCRNA.631 is not found in geneid2symbol or synonyms2ID
SPNCRNA.632 is not found in geneid2symbol or synonyms2ID
SPNCRNA.633 is not found in geneid2symbol or synonyms2ID
SPNCRNA.634 is not found in geneid2symbol or synonyms2ID
SPNCRNA.148 is not found in geneid2symbol or synonyms2ID
SPNCRNA.27 is not found in geneid2symbol or synonyms2ID
SPNCRNA.635 is not found in geneid2symbol or synonyms2ID
SPNCRNA.636 is not found in geneid2symbol or synonyms2ID
SPNCRNA.637 is not found in geneid2symbol or synonyms2ID
SPNCRNA.638 is not found in geneid2symbol or synonyms2ID
SPSNORNA.29 is not found in geneid2symbol or synonyms2ID
SPNCRNA.639 is not found in geneid2symbol or synonyms2ID
SPNCRNA.640 is not found in geneid2symbol or synonyms2ID
SPNCRNA.641 is not found in geneid2symbol or synonyms2ID
SPNCRNA.642 is not found in geneid2symbol or synonyms2ID
SPATRNAPRO.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.643 is not found in geneid2symbol or synonyms2ID
LTR.397023 is not found in geneid2symbol or synonyms2ID
LTR.402409 is not found in geneid2symbol or synonyms2ID
SPNCRNA.644 is not found in geneid2symbol or synonyms2ID
SPNCRNA.645 is not found in geneid2symbol or synonyms2ID
SPSNORNA.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.05 is not found in geneid2symbol or synonyms2ID
SPNCRNA.646 is not found in geneid2symbol or synonyms2ID
SPNCRNA.647 is not found in geneid2symbol or synonyms2ID
SPNCRNA.648 is not found in geneid2symbol or synonyms2ID
SPATRNAVAL.01 is not found in geneid2symbol or synonyms2ID
LTR.446075 is not found in geneid2symbol or synonyms2ID
SPNCRNA.649 is not found in geneid2symbol or synonyms2ID
SPNCRNA.650 is not found in geneid2symbol or synonyms2ID
SPRRNA.11 is not found in geneid2symbol or synonyms2ID
SPNCRNA.651 is not found in geneid2symbol or synonyms2ID
SPNCRNA.652 is not found in geneid2symbol or synonyms2ID
SPNCRNA.653 is not found in geneid2symbol or synonyms2ID
SPNCRNA.551 is not found in geneid2symbol or synonyms2ID
SPNCRNA.654 is not found in geneid2symbol or synonyms2ID
SPNCRNA.47 is not found in geneid2symbol or synonyms2ID
SPNCRNA.655 is not found in geneid2symbol or synonyms2ID
SPNCRNA.656 is not found in geneid2symbol or synonyms2ID
SPNCRNA.657 is not found in geneid2symbol or synonyms2ID
SPNCRNA.658 is not found in geneid2symbol or synonyms2ID
SPNCRNA.659 is not found in geneid2symbol or synonyms2ID
SPSNORNA.02 is not found in geneid2symbol or synonyms2ID
SPSNORNA.03 is not found in geneid2symbol or synonyms2ID
SPSNORNA.04 is not found in geneid2symbol or synonyms2ID
SPSNORNA.05 is not found in geneid2symbol or synonyms2ID
SPSNORNA.06 is not found in geneid2symbol or synonyms2ID
SPNCRNA.552 is not found in geneid2symbol or synonyms2ID
SPNCRNA.660 is not found in geneid2symbol or synonyms2ID
SPNCRNA.661 is not found in geneid2symbol or synonyms2ID
SPNCRNA.154 is not found in geneid2symbol or synonyms2ID
LTR.563321 is not found in geneid2symbol or synonyms2ID
SPNCRNA.155 is not found in geneid2symbol or synonyms2ID
SPNCRNA.662 is not found in geneid2symbol or synonyms2ID
SPNCRNA.553 is not found in geneid2symbol or synonyms2ID
SPNCRNA.663 is not found in geneid2symbol or synonyms2ID
SPNCRNA.664 is not found in geneid2symbol or synonyms2ID
SPNCRNA.156 is not found in geneid2symbol or synonyms2ID
SPNCRNA.665 is not found in geneid2symbol or synonyms2ID
SPNCRNA.666 is not found in geneid2symbol or synonyms2ID
SPNCRNA.667 is not found in geneid2symbol or synonyms2ID
LTR.617366 is not found in geneid2symbol or synonyms2ID
SPNCRNA.668 is not found in geneid2symbol or synonyms2ID
SPNCRNA.669 is not found in geneid2symbol or synonyms2ID
SPNCRNA.670 is not found in geneid2symbol or synonyms2ID
SPAC1D4.07c is not found in geneid2symbol or synonyms2ID
SPNCRNA.671 is not found in geneid2symbol or synonyms2ID
SPNCRNA.672 is not found in geneid2symbol or synonyms2ID
SPNCRNA.79 is not found in geneid2symbol or synonyms2ID
SPNCRNA.673 is not found in geneid2symbol or synonyms2ID
SPNCRNA.674 is not found in geneid2symbol or synonyms2ID
LTR.669786 is not found in geneid2symbol or synonyms2ID
SPNCRNA.675 is not found in geneid2symbol or synonyms2ID
SPNCRNA.158 is not found in geneid2symbol or synonyms2ID
SPNCRNA.676 is not found in geneid2symbol or synonyms2ID
SPATRNAVAL.02 is not found in geneid2symbol or synonyms2ID
SPATRNAGLU.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.677 is not found in geneid2symbol or synonyms2ID
SPNCRNA.678 is not found in geneid2symbol or synonyms2ID
SPNCRNA.679 is not found in geneid2symbol or synonyms2ID
SPNCRNA.680 is not found in geneid2symbol or synonyms2ID
SPNCRNA.681 is not found in geneid2symbol or synonyms2ID
SPNCRNA.159 is not found in geneid2symbol or synonyms2ID
SPNCRNA.682 is not found in geneid2symbol or synonyms2ID
SPNCRNA.683 is not found in geneid2symbol or synonyms2ID
SPNCRNA.684 is not found in geneid2symbol or synonyms2ID
SPNCRNA.685 is not found in geneid2symbol or synonyms2ID
SPNCRNA.686 is not found in geneid2symbol or synonyms2ID
SPNCRNA.687 is not found in geneid2symbol or synonyms2ID
SPNCRNA.688 is not found in geneid2symbol or synonyms2ID
SPNCRNA.689 is not found in geneid2symbol or synonyms2ID
SPNCRNA.690 is not found in geneid2symbol or synonyms2ID
SPNCRNA.691 is not found in geneid2symbol or synonyms2ID
SPNCRNA.692 is not found in geneid2symbol or synonyms2ID
SPNCRNA.693 is not found in geneid2symbol or synonyms2ID
SPNCRNA.694 is not found in geneid2symbol or synonyms2ID
SPNCRNA.695 is not found in geneid2symbol or synonyms2ID
SPRRNA.12 is not found in geneid2symbol or synonyms2ID
SPNCRNA.696 is not found in geneid2symbol or synonyms2ID
SPNCRNA.160 is not found in geneid2symbol or synonyms2ID
SPATRNAALA.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.697 is not found in geneid2symbol or synonyms2ID
SPNCRNA.698 is not found in geneid2symbol or synonyms2ID
SPNCRNA.699 is not found in geneid2symbol or synonyms2ID
SPNCRNA.700 is not found in geneid2symbol or synonyms2ID
SPATRNAGLU.02 is not found in geneid2symbol or synonyms2ID
SPSNRNA.02 is not found in geneid2symbol or synonyms2ID
SPNCRNA.701 is not found in geneid2symbol or synonyms2ID
SPNCRNA.50 is not found in geneid2symbol or synonyms2ID
SPSNRNA.03 is not found in geneid2symbol or synonyms2ID
SPNCRNA.702 is not found in geneid2symbol or synonyms2ID
SPNCRNA.703 is not found in geneid2symbol or synonyms2ID
SPNCRNA.163 is not found in geneid2symbol or synonyms2ID
LTR.1004892 is not found in geneid2symbol or synonyms2ID
SPNCRNA.164 is not found in geneid2symbol or synonyms2ID
SPNCRNA.220 is not found in geneid2symbol or synonyms2ID
SPNCRNA.704 is not found in geneid2symbol or synonyms2ID
SPNCRNA.705 is not found in geneid2symbol or synonyms2ID
SPNCRNA.706 is not found in geneid2symbol or synonyms2ID
SPNCRNA.707 is not found in geneid2symbol or synonyms2ID
LTR.1044522 is not found in geneid2symbol or synonyms2ID
SPNCRNA.708 is not found in geneid2symbol or synonyms2ID
SPNCRNA.709 is not found in geneid2symbol or synonyms2ID
SPNCRNA.166 is not found in geneid2symbol or synonyms2ID
SPNCRNA.710 is not found in geneid2symbol or synonyms2ID
SPATRNASER.01 is not found in geneid2symbol or synonyms2ID
SPATRNAMET.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.711 is not found in geneid2symbol or synonyms2ID
SPNCRNA.712 is not found in geneid2symbol or synonyms2ID
LTR.1118434 is not found in geneid2symbol or synonyms2ID
SPNCRNA.713 is not found in geneid2symbol or synonyms2ID
SPNCRNA.714 is not found in geneid2symbol or synonyms2ID
SPNCRNA.715 is not found in geneid2symbol or synonyms2ID
LTR.1142619 is not found in geneid2symbol or synonyms2ID
SPNCRNA.716 is not found in geneid2symbol or synonyms2ID
LTR.1148611 is not found in geneid2symbol or synonyms2ID
SPNCRNA.717 is not found in geneid2symbol or synonyms2ID
SPNCRNA.718 is not found in geneid2symbol or synonyms2ID
SPNCRNA.719 is not found in geneid2symbol or synonyms2ID
SPNCRNA.168 is not found in geneid2symbol or synonyms2ID
SPNCRNA.720 is not found in geneid2symbol or synonyms2ID
SPNCRNA.721 is not found in geneid2symbol or synonyms2ID
SPATRNAALA.02 is not found in geneid2symbol or synonyms2ID
SPNCRNA.722 is not found in geneid2symbol or synonyms2ID
SPNCRNA.723 is not found in geneid2symbol or synonyms2ID
SPSNORNA.07 is not found in geneid2symbol or synonyms2ID
SPSNORNA.08 is not found in geneid2symbol or synonyms2ID
SPSNORNA.09 is not found in geneid2symbol or synonyms2ID
SPNCRNA.724 is not found in geneid2symbol or synonyms2ID
SPNCRNA.554 is not found in geneid2symbol or synonyms2ID
SPNCRNA.725 is not found in geneid2symbol or synonyms2ID
SPNCRNA.726 is not found in geneid2symbol or synonyms2ID
SPNCRNA.82 is not found in geneid2symbol or synonyms2ID
SPNCRNA.727 is not found in geneid2symbol or synonyms2ID
SPSNORNA.10 is not found in geneid2symbol or synonyms2ID
SPNCRNA.728 is not found in geneid2symbol or synonyms2ID
SPNCRNA.729 is not found in geneid2symbol or synonyms2ID
SPNCRNA.432 is not found in geneid2symbol or synonyms2ID
SPNCRNA.730 is not found in geneid2symbol or synonyms2ID
LTR.1265809 is not found in geneid2symbol or synonyms2ID
SPNCRNA.731 is not found in geneid2symbol or synonyms2ID
SPNCRNA.732 is not found in geneid2symbol or synonyms2ID
SPNCRNA.733 is not found in geneid2symbol or synonyms2ID
SPNCRNA.169 is not found in geneid2symbol or synonyms2ID
SPATRNAPRO.02 is not found in geneid2symbol or synonyms2ID
SPSNORNA.53 is not found in geneid2symbol or synonyms2ID
SPNCRNA.734 is not found in geneid2symbol or synonyms2ID
SPNCRNA.735 is not found in geneid2symbol or synonyms2ID
SPNCRNA.736 is not found in geneid2symbol or synonyms2ID
SPNCRNA.737 is not found in geneid2symbol or synonyms2ID
SPNCRNA.86 is not found in geneid2symbol or synonyms2ID
SPNCRNA.738 is not found in geneid2symbol or synonyms2ID
SPNCRNA.739 is not found in geneid2symbol or synonyms2ID
SPNCRNA.58 is not found in geneid2symbol or synonyms2ID
LTR.1398600 is not found in geneid2symbol or synonyms2ID
SPNCRNA.740 is not found in geneid2symbol or synonyms2ID
SPATRNACYS.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.741 is not found in geneid2symbol or synonyms2ID
LTR.1444293 is not found in geneid2symbol or synonyms2ID
SPATRNAPRO.03 is not found in geneid2symbol or synonyms2ID
SPSNORNA.48 is not found in geneid2symbol or synonyms2ID
LTR.1465332 is not found in geneid2symbol or synonyms2ID
LTR.1469899 is not found in geneid2symbol or synonyms2ID
SPNCRNA.742 is not found in geneid2symbol or synonyms2ID
SPNCRNA.743 is not found in geneid2symbol or synonyms2ID
SPNCRNA.171 is not found in geneid2symbol or synonyms2ID
SPATRNAMET.02 is not found in geneid2symbol or synonyms2ID
SPNCRNA.173 is not found in geneid2symbol or synonyms2ID
SPNCRNA.174 is not found in geneid2symbol or synonyms2ID
SPATRNALEU.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.744 is not found in geneid2symbol or synonyms2ID
SPNCRNA.555 is not found in geneid2symbol or synonyms2ID
SPRRNA.53 is not found in geneid2symbol or synonyms2ID
LTR.1563817 is not found in geneid2symbol or synonyms2ID
LTR.1568384 is not found in geneid2symbol or synonyms2ID
SPNCRNA.80 is not found in geneid2symbol or synonyms2ID
SPNCRNA.745 is not found in geneid2symbol or synonyms2ID
SPNCRNA.175 is not found in geneid2symbol or synonyms2ID
SPNCRNA.81 is not found in geneid2symbol or synonyms2ID
SPNCRNA.746 is not found in geneid2symbol or synonyms2ID
SPATRNATHR.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.747 is not found in geneid2symbol or synonyms2ID
SPNCRNA.748 is not found in geneid2symbol or synonyms2ID
SPNCRNA.749 is not found in geneid2symbol or synonyms2ID
SPNCRNA.750 is not found in geneid2symbol or synonyms2ID
SPATRNAGLY.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.751 is not found in geneid2symbol or synonyms2ID
SPNCRNA.752 is not found in geneid2symbol or synonyms2ID
LTR.1663486 is not found in geneid2symbol or synonyms2ID
SPNCRNA.753 is not found in geneid2symbol or synonyms2ID
SPNCRNA.754 is not found in geneid2symbol or synonyms2ID
SPNCRNA.755 is not found in geneid2symbol or synonyms2ID
SPNCRNA.177 is not found in geneid2symbol or synonyms2ID
SPATRNALYS.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.756 is not found in geneid2symbol or synonyms2ID
SPSNORNA.31 is not found in geneid2symbol or synonyms2ID
SPNCRNA.757 is not found in geneid2symbol or synonyms2ID
SPNCRNA.758 is not found in geneid2symbol or synonyms2ID
SPATRNALYS.02 is not found in geneid2symbol or synonyms2ID
SPATRNATYR.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.759 is not found in geneid2symbol or synonyms2ID
SPNCRNA.556 is not found in geneid2symbol or synonyms2ID
SPATRNAILE.01 is not found in geneid2symbol or synonyms2ID
SPNCRNA.760 is not found in geneid2symbol or synonyms2ID
SPNCRNA.761 is not found in geneid2symbol or synonyms2ID
SPNCRNA.762 is not found in geneid2symbol or synonyms2ID
SPNCRNA.763 is not found in geneid2symbol or synonyms2ID
SPNCRNA.764 is not found in geneid2symbol or synonyms2ID
SPNCRNA.178 is not found in geneid2symbol or synonyms2ID
SPNCRNA.181 is not found in geneid2symbol or synonyms2ID
SPNCRNA.765 is not found in geneid2symbol or synonyms2ID
SPNCRNA.766 is not found in geneid2symbol or synonyms2ID
SPNCRNA.767 is not found in geneid2symbol or synonyms2ID
SPNCRNA.768 is not found in geneid2symbol or synonyms2ID
SPNCRNA.769 is not found in geneid2symbol or synonyms2ID
SPNCRNA.770 is not found in geneid2symbol or synonyms2ID
SPNCRNA.771 is not found in geneid2symbol or synonyms2ID
SPNCRNA.182 is not found in geneid2symbol or synonyms2ID
SPNCRNA.772 is not found in geneid2symbol or synonyms2ID
SPNCRNA.557 is not found in geneid2symbol or synonyms2ID
SPAC110.05 is updated to SPAC110.06
SPNCRNA.773 is not found in geneid2symbol or synonyms2ID
SPNCRNA.774 is not found in geneid2symbol or synonyms2ID
SPNCRNA.775 is not found in geneid2symbol or synonyms2ID
SPNCRNA.776 is not found in geneid2symbol or synonyms2ID
SPNCRNA.777 is not found in geneid2symbol or synonyms2ID
SPNCRNA.778 is not found in geneid2symbol or synonyms2ID
SPNCRNA.779 is not found in geneid2symbol or synonyms2ID
SPNCRNA.780 is not found in geneid2symbol or synonyms2ID
SPNCRNA.781 is not found in geneid2symbol or synonyms2ID
SPNCRNA.782 is not found in geneid2symbol or synonyms2ID
SPNCRNA.783 is not found in geneid2symbol or synonyms2ID
SPNCRNA.784 is not found in geneid2symbol or synonyms2ID
SPNCRNA.530 is not found in geneid2symbol or synonyms2ID
SPNCRNA.785 is not found in geneid2symbol or synonyms2ID
LTR.1999638 is not found in geneid2symbol or synonyms2ID
SPNCRNA.786 is not found in geneid2symbol or synonyms2ID
LTR.2012006 is not found in geneid2symbol or synonyms2ID
SPNCRNA.787 is not found in geneid2symbol or synonyms2ID
SPNCRNA.788 is not found in geneid2symbol or synonyms2ID
SPNCRNA.184 is not found in geneid2symbol or synonyms2ID
SPNCRNA.185 is not found in geneid2symbol or synonyms2ID
SPNCRNA.789 is not found in geneid2symbol or synonyms2ID
SPNCRNA.186 is not found in geneid2symbol or synonyms2ID
SPNCRNA.790 is not found in geneid2symbol or synonyms2ID
SPNCRNA.791 is not found in geneid2symbol or synonyms2ID
SPNCRNA.792 is not found in geneid2symbol or synonyms2ID
SPNCRNA.793 is not found in geneid2symbol or synonyms2ID
SPNCRNA.794 is not found in geneid2symbol or synonyms2ID
SPNCRNA.795 is not found in geneid2symbol or synonyms2ID
SPNCRNA.796 is not found in geneid2symbol or synonyms2ID
SPNCRNA.797 is not found in geneid2symbol or synonyms2ID
SPNCRNA.798 is not found in geneid2symbol or synonyms2ID
SPNCRNA.799 is not found in geneid2symbol or synonyms2ID
SPNCRNA.800 is not found in geneid2symbol or synonyms2ID
SPNCRNA.187 is not found in geneid2symbol or synonyms2ID
LTR.2173899 is not found in geneid2symbol or synonyms2ID
SPNCRNA.801 is not found in geneid2symbol or synonyms2ID
SPNCRNA.802 is not found in geneid2symbol or synonyms2ID
LTR.2186786 is not found in geneid2symbol or synonyms2ID
SPNCRNA.803 is not found in geneid2symbol or synonyms2ID
SPNCRNA.804 is not found in geneid2symbol or synonyms2ID
SPATRNAVAL.03 is not found in geneid2symbol or synonyms2ID
SPNCRNA.805 is not found in geneid2symbol or synonyms2ID
SPNCRNA.188 is not found in geneid2symbol or synonyms2ID

### RNA kinetics

In [81]:
mRNA_kinetics = pd.read_excel("../../resources/Literature/PMID27825301/12864_2016_3237_MOESM22_ESM.xls", sheet_name="Table")
mRNA_kinetics = mRNA_kinetics[["Gene ID", "tAIg", "HL - Mata (5)", "SR - Mata (5)"]].set_index("Gene ID")
mRNA_kinetics.columns = ["tAIg", "mRNA_half_life_minutes", "mRNA_synthesis_rate_per_minute"]
mRNA_kinetics.index = update_sysIDs(mRNA_kinetics.index.tolist(), cfg.gene_meta_file)
coding_gene_mRNA_kinetics = mRNA_kinetics[mRNA_kinetics.index.isin(coding_genes)].copy().dropna().round(3)
coding_gene_mRNA_kinetics = coding_gene_mRNA_kinetics.rename_axis("gene_systematic_id").reset_index().drop_duplicates(subset=["gene_systematic_id"]).set_index("gene_systematic_id")

SPAC110.05 is updated to SPAC110.06
SPBC8E4.02c is not found in geneid2symbol or synonyms2ID
SPCC285.06c is not found in geneid2symbol or synonyms2ID
SPCC306.10 is not found in geneid2symbol or synonyms2ID
SPCC553.05c is not found in geneid2symbol or synonyms2ID
SPCC622.21 is not found in geneid2symbol or synonyms2ID

### Concatenate RNA features

In [82]:
coding_gene_RNA_features_df = pd.concat([coding_gene_mRNA_abundace_statistics, coding_gene_mRNA_kinetics], axis=1, join="outer")

In [49]:
coding_gene_RNA_features_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4977 entries, SPAC1002.01 to SPMIT.11
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   mean_EMM_Nitrogen_Starved_Cell_RNA_Abundance  4969 non-null   float64
 1   mean_EMM_Proliferating_Cell_RNA_Abundance     4969 non-null   float64
 2   std_EMM_Nitrogen_Starved_Cell_RNA_Abundance   4969 non-null   float64
 3   std_EMM_Proliferating_Cell_RNA_Abundance      4969 non-null   float64
 4   cv_EMM_Nitrogen_Starved_Cell_RNA_Abundance    4969 non-null   float64
 5   cv_EMM_Proliferating_Cell_RNA_Abundance       4969 non-null   float64
 6   tAIg                                          4637 non-null   float64
 7   mRNA_half_life_minutes                        4637 non-null   float64
 8   mRNA_synthesis_rate_per_minute                4637 non-null   float64
dtypes: float64(9)
memory usage: 388.8+ KB

## 4.3 Protein-level features

### Protein basic properties

In [50]:
protein_metadata = cfg.protein_meta

### Protein features from the peptide sequences

In [51]:
protein_features_from_peptide_sequences = extract_protein_features_from_peptide_sequence(cfg.PomBase_resource_dir / "genome_sequence_and_features" / "peptide.fa")

Warning: Stop codon found in sequence of SPAC2E12.05. Truncating at first stop codon.

### Protein abundance

In [85]:
gene_abundance = pd.read_csv(cfg.PomBase_resource_dir / "RNA_metadata" / "quantitative_gene_expression.tsv", sep="\t")
EMM_proliferating_cell_protein_abundance = gene_abundance.query("reference == 'PMID:23101633' and type == 'protein' and condition == 'glucose MM,standard temperature'")[["gene_systematic_id", "copies_per_cell"]].dropna().astype({"copies_per_cell": float})
EMMN_quiescent_cell_protein_abundance = gene_abundance.query("reference == 'PMID:23101633' and type == 'protein' and condition == 'glucose MM,nitrogen absent,standard temperature'")[["gene_systematic_id", "copies_per_cell"]].dropna().astype({"copies_per_cell": float})
protein_abundance = pd.merge(EMM_proliferating_cell_protein_abundance, EMMN_quiescent_cell_protein_abundance, left_on="gene_systematic_id", right_on="gene_systematic_id", suffixes=("_EMM_Proliferating_Cell", "_EMMN_Quiescent_Cell")).set_index("gene_systematic_id")

### Protein turnover

In [86]:
protein_kinetics = pd.read_excel("../../resources/Literature/PMID25466257/1-s2.0-S2211124714009346-mmc3.xlsx", na_values=["n.d."]).dropna(subset=["Degradation rates (min-1)", "t1/2 (min)"])
protein_kinetics["ENSG"] = protein_kinetics["ENSG"].fillna(protein_kinetics["Gene name"])
protein_kinetics = protein_kinetics[["ENSG", "t1/2 (min)"]].set_index("t1/2 (min)")
protein_kinetics = protein_kinetics["ENSG"].str.split(";").explode().reset_index()
protein_kinetics["gene_systeamtic_id"] = update_sysIDs(protein_kinetics["ENSG"].tolist(), cfg.gene_meta_file)
protein_kinetics = protein_kinetics.drop_duplicates(subset=["gene_systeamtic_id"])

lsd90 is updated to SPBC16E9.16c
psm1 is updated to SPBC29A10.04
tea4 is updated to SPBC1706.01
rhp16 is updated to SPCC330.01c
nnf1 is updated to SPAC29E6.04
met6 is updated to SPBC56F2.11
med10 is updated to SPBC31F10.09c
did2 is updated to SPBC13G1.12
rtx2 is not found in geneid2symbol or synonyms2ID
utp16 is updated to SPBP8B7.10c
tfg1 is updated to SPCC1620.09c
mrpl38 is updated to SPBC887.07
abh1 is updated to SPBC13G1.04c
rex2 is updated to SPBC1347.07
cym1 is updated to SPBC119.17
med11 is updated to SPAC644.10
rsm10 is updated to SPBC211.01
tim8 is updated to SPAC13G6.04
prp10 is updated to SPAC27F1.09c
ucp8 is updated to SPBC83.01
trx2 is updated to SPBC12D12.07c
snu23 is updated to SPAC22F3.11c
lub1 is updated to SPBC887.04c
rrp7 is updated to SPBC776.17
cox2 is updated to SPMIT.11
CoxII is not found in geneid2symbol or synonyms2ID
COXII is not found in geneid2symbol or synonyms2ID
cwf10 is updated to SPBC215.12
erb1 is updated to SPBC4F6.13c
rhp51 is updated to SPAC644.14c
gtp1 is updated to SPBC354.01
hem12 is updated to SPCC4B3.05c
mcm4 is updated to SPCC16A11.17
cwf22 is updated to SPBC13E7.01
tcg1 is updated to SPBC660.11
lea1 is updated to SPBC1861.08c
mas2 is updated to SPBC18E5.12c
spj1 is not found in geneid2symbol or synonyms2ID
hts1 is not found in geneid2symbol or synonyms2ID
moe1 is updated to SPAC637.07
vps901 is updated to SPBC4F6.10
pdf1 is updated to SPBC530.12c
mgm101 is updated to SPBC30D10.08
ade9 is updated to SPBC2G2.08
fol1 is updated to SPBC1734.03
retrotransposon Tf1-107 is not found in geneid2symbol or synonyms2ID
tef3 is updated to SPCC417.08
tam41 is updated to SPBC1A4.06c
dna2 is updated to SPBC16D10.04c
qcr9 is updated to SPCC1682.01
gto2 is updated to SPAC30D11.01c
mcm5 is updated to SPAC1B2.05

### pLDDT features

In [54]:
pLDDTs = pLDDT_statistics_report(
    structure_dir=ALPHAFOLD_DATABASE_DIR,
    structure_format="pdb.gz"
)

100%|██████████| 5196/5196 [06:14<00:00, 13.88it/s]

In [55]:
pLDDTs["Systematic_ID"] = pLDDTs["uniprot_id"].map(uniprot2id)

### Domain features

In [87]:
protein_domains = pd.read_csv(cfg.PomBase_resource_dir / "Protein_features" / "protein_families_and_domains.tsv", sep="\t")
pfam_domain_counts = protein_domains.query("database == 'PFAM'").groupby("systematic_id").size().rename("PFAM_domain_count")

### Concatenate protein features

In [88]:
selected_protein_features_from_peptide = [
    'aromaticity', 'aliphatic_index', 'gravy', 'flexibility',
    'instability_index', 'aa_percent_Ala', 'aa_percent_Cys', 'aa_percent_Asp',
    'aa_percent_Glu', 'aa_percent_Phe', 'aa_percent_Gly', 'aa_percent_His',
    'aa_percent_Ile', 'aa_percent_Lys', 'aa_percent_Leu', 'aa_percent_Met',
    'aa_percent_Asn', 'aa_percent_Pro', 'aa_percent_Gln', 'aa_percent_Arg',
    'aa_percent_Ser', 'aa_percent_Thr', 'aa_percent_Val', 'aa_percent_Trp',
    'aa_percent_Tyr'
]

coding_gene_protein_features_df = protein_metadata.merge(
    protein_features_from_peptide_sequences.set_index("Gene_id")[selected_protein_features_from_peptide], 
    left_index=True, 
    right_index=True, 
    how="outer"
).merge(
    protein_abundance,
    left_index=True,
    right_index=True,
    how="outer"
).merge(
    protein_kinetics.set_index("gene_systeamtic_id")[['t1/2 (min)']],
    left_index=True,
    right_index=True,
    how="outer"
).merge(
    pLDDTs.set_index("Systematic_ID")[['mean_pLDDT', 'std_pLDDT', 'cv_pLDDT']],
    left_index=True,
    right_index=True,
    how="outer"
).join(
    pfam_domain_counts
)

coding_gene_protein_features_df = coding_gene_protein_features_df[coding_gene_protein_features_df.index.isin(coding_genes)].copy()

In [89]:
coding_gene_protein_features_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5134 entries, SPAC1002.01 to SPMTR.02
Data columns (total 37 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Mass (kDa)                              5134 non-null   float64
 1   pI                                      5134 non-null   float64
 2   Charge                                  5134 non-null   float64
 3   Residues                                5134 non-null   float64
 4   CAI                                     5134 non-null   float64
 5   aromaticity                             5134 non-null   float64
 6   aliphatic_index                         5134 non-null   float64
 7   gravy                                   5134 non-null   float64
 8   flexibility                             5134 non-null   float64
 9   instability_index                       5134 non-null   float64
 10  aa_percent_Ala                          5134 non-null   float64
 11  aa_percent_Cys                          5134 non-null   float64
 12  aa_percent_Asp                          5134 non-null   float64
 13  aa_percent_Glu                          5134 non-null   float64
 14  aa_percent_Phe                          5134 non-null   float64
 15  aa_percent_Gly                          5134 non-null   float64
 16  aa_percent_His                          5134 non-null   float64
 17  aa_percent_Ile                          5134 non-null   float64
 18  aa_percent_Lys                          5134 non-null   float64
 19  aa_percent_Leu                          5134 non-null   float64
 20  aa_percent_Met                          5134 non-null   float64
 21  aa_percent_Asn                          5134 non-null   float64
 22  aa_percent_Pro                          5134 non-null   float64
 23  aa_percent_Gln                          5134 non-null   float64
 24  aa_percent_Arg                          5134 non-null   float64
 25  aa_percent_Ser                          5134 non-null   float64
 26  aa_percent_Thr                          5134 non-null   float64
 27  aa_percent_Val                          5134 non-null   float64
 28  aa_percent_Trp                          5134 non-null   float64
 29  aa_percent_Tyr                          5134 non-null   float64
 30  copies_per_cell_EMM_Proliferating_Cell  2500 non-null   float64
 31  copies_per_cell_EMMN_Quiescent_Cell     2500 non-null   float64
 32  t1/2 (min)                              3012 non-null   float64
 33  mean_pLDDT                              5097 non-null   float64
 34  std_pLDDT                               5097 non-null   float64
 35  cv_pLDDT                                5097 non-null   float64
 36  PFAM_domain_count                       4557 non-null   float64
dtypes: float64(37)
memory usage: 1.5+ MB

## 4.4 Evolutionary-level features

### Ortholog count

In [9]:
def get_ortholog_counts(ortholog_file: Path) -> pd.Series:
    """Get the number of orthologs for each gene from the ortholog file."""
    ortholog_df = pd.read_csv(ortholog_file, sep="\t", index_col=0, header=None, names=["gene_systematic_id", "orthologs"], na_values="NONE")
    ortholog_df.index = ortholog_df.index.str.split("(").str[0]
    ortholog_counts = ortholog_df["orthologs"].str.split("|").apply(lambda x: len(x) if isinstance(x, list) else 0 )
    return ortholog_counts

num_of_orthologs_with_japonicus = get_ortholog_counts(cfg.PomBase_resource_dir / "curated_orthologs" / "pombe_japonicus_orthologs.txt")
num_of_orthologs_with_cerevisiae = get_ortholog_counts(cfg.PomBase_resource_dir / "curated_orthologs" / "pombe_cerevisiae_orthologs.txt")
num_of_orthologs_with_human = get_ortholog_counts(cfg.PomBase_resource_dir / "curated_orthologs" / "pombe_human_orthologs.txt")

### Paralog count

In [10]:
pombe_paralogs = pd.read_csv("../../resources/Ensemble/pombe_paralog_from_ensemble_biomart_export.tsv", sep="\t")

paralog_count = pombe_paralogs.query("`Gene stable ID` in @coding_genes").groupby(["Gene stable ID", "Gene name"]).apply(lambda sub_df: sub_df.shape[0], include_groups=False).rename("paralog_count")
paralog_count["gene_systematic_id"] = update_sysIDs(paralog_count.index.get_level_values("Gene stable ID").tolist(), cfg.gene_meta_file)

### Evolution Rate

In [17]:
evolutionary_rate = pd.read_excel("../../resources/Literature/PMID21511999/1203357-rhind_tables.xls", sheet_name="S30", skiprows=[0,1])
evolutionary_rate["gene_systematic_id"] = update_sysIDs(evolutionary_rate["Genes"].str.split(";").str[0].tolist(), cfg.gene_meta_file)

### phyloP and divergence scores

In [22]:
phyloP_and_divergence = pd.read_excel("../../resources/Literature/PMID31077324/Supplementary-tables-fission-yeast-transposon-2018-12-05.xlsx", sheet_name="Table 2", skiprows=list(range(14)))
phyloP_and_divergence = phyloP_and_divergence.drop_duplicates(subset=["gene"])
phyloP_and_divergence["gene_systematic_id"] = update_sysIDs(phyloP_and_divergence["gene"].tolist(), cfg.gene_meta_file)

SPAC110.05 is updated to SPAC110.06
SPAC1D4.07c is not found in geneid2symbol or synonyms2ID
SPAC27E2.13 is not found in geneid2symbol or synonyms2ID
SPAC4H3.12c is not found in geneid2symbol or synonyms2ID
SPAC823.02 is updated to SPAC823.17
SPBC1685.12c is not found in geneid2symbol or synonyms2ID
SPBC32F12.17 is not found in geneid2symbol or synonyms2ID
SPBC354.11c is not found in geneid2symbol or synonyms2ID
SPBC36.13 is not found in geneid2symbol or synonyms2ID
SPBC713.13 is updated to SPBC713.14c
SPBC8E4.02c is not found in geneid2symbol or synonyms2ID
SPCC1672.14 is not found in geneid2symbol or synonyms2ID
SPCC188.05 is not found in geneid2symbol or synonyms2ID
SPCC285.06c is not found in geneid2symbol or synonyms2ID
SPCC306.10 is not found in geneid2symbol or synonyms2ID
SPCC417.04 is not found in geneid2symbol or synonyms2ID
SPCC553.05c is not found in geneid2symbol or synonyms2ID
SPCC622.05 is not found in geneid2symbol or synonyms2ID
SPCC622.21 is not found in geneid2symbol or synonyms2ID
SPATRNAALA.02 is not found in geneid2symbol or synonyms2ID
SPATRNAALA.03 is not found in geneid2symbol or synonyms2ID
SPSNRNA.04 is not found in geneid2symbol or synonyms2ID
SPSNORNA.35 is not found in geneid2symbol or synonyms2ID
SPSNORNA.37 is not found in geneid2symbol or synonyms2ID
SPSNORNA.38 is not found in geneid2symbol or synonyms2ID
SPSNORNA.39 is not found in geneid2symbol or synonyms2ID
SPSNORNA.40 is not found in geneid2symbol or synonyms2ID
SPSNORNA.42 is not found in geneid2symbol or synonyms2ID
SPSNORNA.43 is not found in geneid2symbol or synonyms2ID
SPSNORNA.44 is not found in geneid2symbol or synonyms2ID
SPSNORNA.45 is not found in geneid2symbol or synonyms2ID
SPSNORNA.46 is not found in geneid2symbol or synonyms2ID
SPSNORNA.53 is not found in geneid2symbol or synonyms2ID
SPSNRNA.01 is not found in geneid2symbol or synonyms2ID
SPSNRNA.07 is not found in geneid2symbol or synonyms2ID
SPAC1F12.03c is not found in geneid2symbol or synonyms2ID
SPAC212.05c is not found in geneid2symbol or synonyms2ID
SPAC212.07c is not found in geneid2symbol or synonyms2ID
SPAC212.09c is not found in geneid2symbol or synonyms2ID
SPAC212.10 is not found in geneid2symbol or synonyms2ID
SPAC23D3.05c is not found in geneid2symbol or synonyms2ID
SPAC977.13c is not found in geneid2symbol or synonyms2ID
SPAPB24D3.05c is not found in geneid2symbol or synonyms2ID
SPBC1348.11 is not found in geneid2symbol or synonyms2ID
SPBC1706.02c is not found in geneid2symbol or synonyms2ID
SPBPB10D8.03 is not found in geneid2symbol or synonyms2ID
SPCC132.05c is not found in geneid2symbol or synonyms2ID
SPCC1450.01c is not found in geneid2symbol or synonyms2ID
SPCC188.10c is not found in geneid2symbol or synonyms2ID
SPCC18B5.02c is not found in geneid2symbol or synonyms2ID
SPCC576.16c is not found in geneid2symbol or synonyms2ID
SPCC663.07c is not found in geneid2symbol or synonyms2ID
SPCC830.02 is not found in geneid2symbol or synonyms2ID
SPCP20C8.03 is not found in geneid2symbol or synonyms2ID
SPMITTRNASER.02 is not found in geneid2symbol or synonyms2ID
SPBTRNATYR.04 is not found in geneid2symbol or synonyms2ID
SPMITTRNAALA.01 is not found in geneid2symbol or synonyms2ID
SPMITTRNAGLU.01 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLY.04 is not found in geneid2symbol or synonyms2ID
SPBTRNAALA.07 is not found in geneid2symbol or synonyms2ID
SPRRNA.30 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLY.06 is not found in geneid2symbol or synonyms2ID
SPATRNAARG.03 is not found in geneid2symbol or synonyms2ID
SPBTRNAARG.05 is not found in geneid2symbol or synonyms2ID
SPRRNA.33 is not found in geneid2symbol or synonyms2ID
SPSNORNA.20 is not found in geneid2symbol or synonyms2ID
SPATRNALEU.03 is not found in geneid2symbol or synonyms2ID
SPBTRNALEU.08 is not found in geneid2symbol or synonyms2ID
SPCTRNAVAL.12 is not found in geneid2symbol or synonyms2ID
SPRRNA.12 is not found in geneid2symbol or synonyms2ID
SPCTRNAARG.10 is not found in geneid2symbol or synonyms2ID
SPCTRNAASP.05 is not found in geneid2symbol or synonyms2ID
SPCTRNASER.11 is not found in geneid2symbol or synonyms2ID
SPATRNACYS.02 is not found in geneid2symbol or synonyms2ID
SPCTRNAILE.09 is not found in geneid2symbol or synonyms2ID
SPCTRNAASP.06 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLY.05 is not found in geneid2symbol or synonyms2ID
SPBTRNAARG.04 is not found in geneid2symbol or synonyms2ID
SPCTRNAGLY.11 is not found in geneid2symbol or synonyms2ID
SPSNORNA.31 is not found in geneid2symbol or synonyms2ID
SPRRNA.06 is not found in geneid2symbol or synonyms2ID
SPATRNAALA.01 is not found in geneid2symbol or synonyms2ID
SPBTRNATHR.07 is not found in geneid2symbol or synonyms2ID
SPCTRNAVAL.10 is not found in geneid2symbol or synonyms2ID
SPRRNA.19 is not found in geneid2symbol or synonyms2ID
SPRRNA.27 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLN.04 is not found in geneid2symbol or synonyms2ID
SPATRNAPRO.01 is not found in geneid2symbol or synonyms2ID
SPATRNALYS.02 is not found in geneid2symbol or synonyms2ID
SPCTRNASER.08 is not found in geneid2symbol or synonyms2ID
SPRRNA.34 is not found in geneid2symbol or synonyms2ID
SPSNORNA.41 is not found in geneid2symbol or synonyms2ID
SPRRNA.55 is not found in geneid2symbol or synonyms2ID
SPATRNATYR.01 is not found in geneid2symbol or synonyms2ID
SPATRNAGLU.02 is not found in geneid2symbol or synonyms2ID
SPBTRNAHIS.02 is not found in geneid2symbol or synonyms2ID
SPSNRNA.06 is not found in geneid2symbol or synonyms2ID
SPBTRNALEU.10 is not found in geneid2symbol or synonyms2ID
SPCTRNAGLY.12 is not found in geneid2symbol or synonyms2ID
SPBTRNAASN.02 is not found in geneid2symbol or synonyms2ID
SPRRNA.39 is not found in geneid2symbol or synonyms2ID
SPSNORNA.23 is not found in geneid2symbol or synonyms2ID
SPATRNAALA.04 is not found in geneid2symbol or synonyms2ID
SPATRNAILE.02 is not found in geneid2symbol or synonyms2ID
SPATRNASER.04 is not found in geneid2symbol or synonyms2ID
SPATRNAILE.04 is not found in geneid2symbol or synonyms2ID
SPRRNA.04 is not found in geneid2symbol or synonyms2ID
SPSNORNA.25 is not found in geneid2symbol or synonyms2ID
SPRRNA.20 is not found in geneid2symbol or synonyms2ID
SPBCPT2R1.05c is not found in geneid2symbol or synonyms2ID
SPBCPT2R1.06c is not found in geneid2symbol or synonyms2ID
SPBCPT2R1.07c is not found in geneid2symbol or synonyms2ID
SPBCPT2R1.10 is not found in geneid2symbol or synonyms2ID
SPSNORNA.17 is not found in geneid2symbol or synonyms2ID
SPRRNA.10 is not found in geneid2symbol or synonyms2ID
SPRRNA.47 is not found in geneid2symbol or synonyms2ID
SPRRNA.50 is not found in geneid2symbol or synonyms2ID
SPRRNA.43 is not found in geneid2symbol or synonyms2ID
SPRRNA.48 is not found in geneid2symbol or synonyms2ID
SPRRNA.51 is not found in geneid2symbol or synonyms2ID
SPRRNA.44 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLY.09 is not found in geneid2symbol or synonyms2ID
SPATRNAMET.03 is not found in geneid2symbol or synonyms2ID
SPCTRNAPHE.04 is not found in geneid2symbol or synonyms2ID
SPCTRNAPRO.09 is not found in geneid2symbol or synonyms2ID
SPATRNAARG.01 is not found in geneid2symbol or synonyms2ID
SPSNORNA.49 is not found in geneid2symbol or synonyms2ID
SPRRNA.14 is not found in geneid2symbol or synonyms2ID
SPBTRNALYS.08 is not found in geneid2symbol or synonyms2ID
SPCTRNAARG.09 is not found in geneid2symbol or synonyms2ID
SPRRNA.26 is not found in geneid2symbol or synonyms2ID
SPSNORNA.12 is not found in geneid2symbol or synonyms2ID
SPBTRNAHIS.01 is not found in geneid2symbol or synonyms2ID
SPRRNA.28 is not found in geneid2symbol or synonyms2ID
SPBC18E5.15 is not found in geneid2symbol or synonyms2ID
SPCTRNASER.10 is not found in geneid2symbol or synonyms2ID
SPATRNAARG.02 is not found in geneid2symbol or synonyms2ID
SPBTRNAPRO.04 is not found in geneid2symbol or synonyms2ID
SPCTRNAHIS.03 is not found in geneid2symbol or synonyms2ID
SPATRNAASP.02 is not found in geneid2symbol or synonyms2ID
SPCTRNAASN.05 is not found in geneid2symbol or synonyms2ID
SPATRNAPHE.02 is not found in geneid2symbol or synonyms2ID
SPSNORNA.30 is not found in geneid2symbol or synonyms2ID
SPBTRNAPRO.07 is not found in geneid2symbol or synonyms2ID
SPRRNA.03 is not found in geneid2symbol or synonyms2ID
SPBTRNATHR.06 is not found in geneid2symbol or synonyms2ID
SPSNORNA.15 is not found in geneid2symbol or synonyms2ID
SPATRNAALA.05 is not found in geneid2symbol or synonyms2ID
SPSNORNA.16 is not found in geneid2symbol or synonyms2ID
SPCTRNAHIS.04 is not found in geneid2symbol or synonyms2ID
SPBTRNATYR.02 is not found in geneid2symbol or synonyms2ID
SPBTRNALEU.09 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLY.07 is not found in geneid2symbol or synonyms2ID
SPATRNALYS.04 is not found in geneid2symbol or synonyms2ID
SPATRNASER.01 is not found in geneid2symbol or synonyms2ID
SPATRNAMET.01 is not found in geneid2symbol or synonyms2ID
SPCTRNAGLY.10 is not found in geneid2symbol or synonyms2ID
SPSNORNA.05 is not found in geneid2symbol or synonyms2ID
SPSNORNA.06 is not found in geneid2symbol or synonyms2ID
SPBTRNAVAL.06 is not found in geneid2symbol or synonyms2ID
SPRRNA.29 is not found in geneid2symbol or synonyms2ID
SPBTRNAALA.10 is not found in geneid2symbol or synonyms2ID
SPBTRNAILE.07 is not found in geneid2symbol or synonyms2ID
SPBTRNATYR.03 is not found in geneid2symbol or synonyms2ID
SPSNORNA.54 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLY.08 is not found in geneid2symbol or synonyms2ID
SPATRNALYS.05 is not found in geneid2symbol or synonyms2ID
SPBTRNAILE.08 is not found in geneid2symbol or synonyms2ID
SPRRNA.15 is not found in geneid2symbol or synonyms2ID
SPRRNA.17 is not found in geneid2symbol or synonyms2ID
SPCTRNAGLU.09 is not found in geneid2symbol or synonyms2ID
SPBTRNAARG.07 is not found in geneid2symbol or synonyms2ID
SPMITTRNATYR.01 is not found in geneid2symbol or synonyms2ID
SPATRNATRP.01 is not found in geneid2symbol or synonyms2ID
SPMITTRNAILE.02 is not found in geneid2symbol or synonyms2ID
SPCTRNATHR.10 is not found in geneid2symbol or synonyms2ID
SPRRNA.32 is not found in geneid2symbol or synonyms2ID
SPBPB21E7.06 is not found in geneid2symbol or synonyms2ID
SPCTRNASER.07 is not found in geneid2symbol or synonyms2ID
SPATRNACYS.01 is not found in geneid2symbol or synonyms2ID
SPRRNA.52 is not found in geneid2symbol or synonyms2ID
SPCTRNAARG.08 is not found in geneid2symbol or synonyms2ID
SPSNORNA.10 is not found in geneid2symbol or synonyms2ID
SPRRNA.01 is not found in geneid2symbol or synonyms2ID
SPSNORNA.32 is not found in geneid2symbol or synonyms2ID
SPATRNAGLU.04 is not found in geneid2symbol or synonyms2ID
SPCTRNAALA.12 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLU.08 is not found in geneid2symbol or synonyms2ID
SPCTRNASER.09 is not found in geneid2symbol or synonyms2ID
SPSNORNA.13 is not found in geneid2symbol or synonyms2ID
SPATRNAGLY.02 is not found in geneid2symbol or synonyms2ID
SPCTRNAARG.11 is not found in geneid2symbol or synonyms2ID
SPCTRNALEU.11 is not found in geneid2symbol or synonyms2ID
SPSNORNA.29 is not found in geneid2symbol or synonyms2ID
SPRRNA.05 is not found in geneid2symbol or synonyms2ID
SPCTRNAARG.12 is not found in geneid2symbol or synonyms2ID
SPCTRNAVAL.09 is not found in geneid2symbol or synonyms2ID
SPCTRNATHR.08 is not found in geneid2symbol or synonyms2ID
SPSNORNA.52 is not found in geneid2symbol or synonyms2ID
SPCTRNAGLU.10 is not found in geneid2symbol or synonyms2ID
SPCC548.02c is not found in geneid2symbol or synonyms2ID
SPCTRNATHR.09 is not found in geneid2symbol or synonyms2ID
SPMITTRNATRP.01 is not found in geneid2symbol or synonyms2ID
SPCTRNAARG.13 is not found in geneid2symbol or synonyms2ID
SPCTRNAASP.07 is not found in geneid2symbol or synonyms2ID
SPSNORNA.07 is not found in geneid2symbol or synonyms2ID
SPMITTRNAPRO.01 is not found in geneid2symbol or synonyms2ID
SPATRNALEU.02 is not found in geneid2symbol or synonyms2ID
SPRRNA.07 is not found in geneid2symbol or synonyms2ID
SPATRNAMET.02 is not found in geneid2symbol or synonyms2ID
SPCTRNALYS.11 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLY.03 is not found in geneid2symbol or synonyms2ID
SPSNORNA.36 is not found in geneid2symbol or synonyms2ID
SPBTRNASER.06 is not found in geneid2symbol or synonyms2ID
SPSNORNA.21 is not found in geneid2symbol or synonyms2ID
SPBTRNALEU.05 is not found in geneid2symbol or synonyms2ID
SPSNRNA.02 is not found in geneid2symbol or synonyms2ID
SPATRNAVAL.03 is not found in geneid2symbol or synonyms2ID
SPBTRNAPRO.08 is not found in geneid2symbol or synonyms2ID
SPBTRNAMET.04 is not found in geneid2symbol or synonyms2ID
SPBPB21E7.08 is not found in geneid2symbol or synonyms2ID
SPRRNA.49 is not found in geneid2symbol or synonyms2ID
SPATRNAGLU.03 is not found in geneid2symbol or synonyms2ID
SPSNORNA.27 is not found in geneid2symbol or synonyms2ID
SPATRNATHR.01 is not found in geneid2symbol or synonyms2ID
SPRRNA.54 is not found in geneid2symbol or synonyms2ID
SPATRNATHR.03 is not found in geneid2symbol or synonyms2ID
SPATRNAVAL.02 is not found in geneid2symbol or synonyms2ID
SPRRNA.36 is not found in geneid2symbol or synonyms2ID
SPBTRNAASP.04 is not found in geneid2symbol or synonyms2ID
SPCTRNAGLN.06 is not found in geneid2symbol or synonyms2ID
SPBTRNATRP.03 is not found in geneid2symbol or synonyms2ID
SPBTRNALYS.07 is not found in geneid2symbol or synonyms2ID
SPSNORNA.33 is not found in geneid2symbol or synonyms2ID
SPSNORNA.18 is not found in geneid2symbol or synonyms2ID
SPSNORNA.01 is not found in geneid2symbol or synonyms2ID
SPBTRNAPRO.06 is not found in geneid2symbol or synonyms2ID
SPATRNACYS.03 is not found in geneid2symbol or synonyms2ID
SPATRNAPHE.01 is not found in geneid2symbol or synonyms2ID
SPRRNA.35 is not found in geneid2symbol or synonyms2ID
SPATRNAVAL.01 is not found in geneid2symbol or synonyms2ID
SPATRNAVAL.04 is not found in geneid2symbol or synonyms2ID
SPCTRNALEU.13 is not found in geneid2symbol or synonyms2ID
SPRRNA.11 is not found in geneid2symbol or synonyms2ID
SPSNORNA.19 is not found in geneid2symbol or synonyms2ID
SPATRNATHR.04 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLN.03 is not found in geneid2symbol or synonyms2ID
SPSNORNA.26 is not found in geneid2symbol or synonyms2ID
SPATRNAGLY.01 is not found in geneid2symbol or synonyms2ID
SPBTRNASER.05 is not found in geneid2symbol or synonyms2ID
SPCTRNAPHE.05 is not found in geneid2symbol or synonyms2ID
SPBTRNAMET.06 is not found in geneid2symbol or synonyms2ID
SPMITTRNAVAL.01 is not found in geneid2symbol or synonyms2ID
SPRRNA.41 is not found in geneid2symbol or synonyms2ID
SPRRNA.40 is not found in geneid2symbol or synonyms2ID
SPMITTRNAARG.02 is not found in geneid2symbol or synonyms2ID
SPBTRNALYS.09 is not found in geneid2symbol or synonyms2ID
SPATRNALEU.04 is not found in geneid2symbol or synonyms2ID
SPBTRNALEU.06 is not found in geneid2symbol or synonyms2ID
SPATRNAPRO.02 is not found in geneid2symbol or synonyms2ID
SPRRNA.46 is not found in geneid2symbol or synonyms2ID
SPMITTRNATHR.01 is not found in geneid2symbol or synonyms2ID
SPSNORNA.02 is not found in geneid2symbol or synonyms2ID
SPRRNA.45 is not found in geneid2symbol or synonyms2ID
SPCTRNAASP.08 is not found in geneid2symbol or synonyms2ID
SPATRNAILE.03 is not found in geneid2symbol or synonyms2ID
SPMITTRNAASN.01 is not found in geneid2symbol or synonyms2ID
SPBTRNAASN.01 is not found in geneid2symbol or synonyms2ID
SPRRNA.31 is not found in geneid2symbol or synonyms2ID
SPBTRNAMET.05 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLN.01 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLN.02 is not found in geneid2symbol or synonyms2ID
SPSNORNA.50 is not found in geneid2symbol or synonyms2ID
SPMITTRNAARG.01 is not found in geneid2symbol or synonyms2ID
SPBTRNALEU.07 is not found in geneid2symbol or synonyms2ID
SPRRNA.37 is not found in geneid2symbol or synonyms2ID
SPSNORNA.03 is not found in geneid2symbol or synonyms2ID
SPSNORNA.04 is not found in geneid2symbol or synonyms2ID
SPMITTRNAPHE.01 is not found in geneid2symbol or synonyms2ID
SPATRNATHR.02 is not found in geneid2symbol or synonyms2ID
SPBTRNAPRO.05 is not found in geneid2symbol or synonyms2ID
SPSNORNA.34 is not found in geneid2symbol or synonyms2ID
SPSNORNA.24 is not found in geneid2symbol or synonyms2ID
SPSNORNA.14 is not found in geneid2symbol or synonyms2ID
SPBTRNAPHE.03 is not found in geneid2symbol or synonyms2ID
SPSNRNA.05 is not found in geneid2symbol or synonyms2ID
SPCTRNASER.13 is not found in geneid2symbol or synonyms2ID
SPATRNASER.02 is not found in geneid2symbol or synonyms2ID
SPATRNALYS.01 is not found in geneid2symbol or synonyms2ID
SPBTRNAALA.11 is not found in geneid2symbol or synonyms2ID
SPMITTRNAILE.01 is not found in geneid2symbol or synonyms2ID
SPRRNA.16 is not found in geneid2symbol or synonyms2ID
SPMITTRNACYS.01 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLU.07 is not found in geneid2symbol or synonyms2ID
SPATRNATHR.05 is not found in geneid2symbol or synonyms2ID
SPATRNAILE.01 is not found in geneid2symbol or synonyms2ID
SPMITTRNALEU.01 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLU.05 is not found in geneid2symbol or synonyms2ID
SPATRNAALA.06 is not found in geneid2symbol or synonyms2ID
SPRRNA.53 is not found in geneid2symbol or synonyms2ID
SPMITTRNALEU.02 is not found in geneid2symbol or synonyms2ID
SPSNORNA.11 is not found in geneid2symbol or synonyms2ID
SPBTRNALYS.06 is not found in geneid2symbol or synonyms2ID
SPATRNAPRO.03 is not found in geneid2symbol or synonyms2ID
SPCTRNASER.12 is not found in geneid2symbol or synonyms2ID
SPSNORNA.48 is not found in geneid2symbol or synonyms2ID
SPMITTRNASER.01 is not found in geneid2symbol or synonyms2ID
SPCTRNALEU.12 is not found in geneid2symbol or synonyms2ID
SPRRNA.18 is not found in geneid2symbol or synonyms2ID
SPRRNA.02 is not found in geneid2symbol or synonyms2ID
SPMITTRNAMET.01 is not found in geneid2symbol or synonyms2ID
SPSNORNA.22 is not found in geneid2symbol or synonyms2ID
SPSNRNA.03 is not found in geneid2symbol or synonyms2ID
SPMITTRNAGLY.01 is not found in geneid2symbol or synonyms2ID
SPATRNALEU.01 is not found in geneid2symbol or synonyms2ID
SPMITTRNAHIS.01 is not found in geneid2symbol or synonyms2ID
SPSNORNA.09 is not found in geneid2symbol or synonyms2ID
SPSNORNA.47 is not found in geneid2symbol or synonyms2ID
SPMITTRNAGLN.01 is not found in geneid2symbol or synonyms2ID
SPRRNA.24 is not found in geneid2symbol or synonyms2ID
SPBTRNAVAL.08 is not found in geneid2symbol or synonyms2ID
SPCTRNALYS.12 is not found in geneid2symbol or synonyms2ID
SPCTRNAVAL.11 is not found in geneid2symbol or synonyms2ID
SPCTRNAASN.06 is not found in geneid2symbol or synonyms2ID
SPRRNA.38 is not found in geneid2symbol or synonyms2ID
SPBTRNAVAL.07 is not found in geneid2symbol or synonyms2ID
SPATRNAGLU.01 is not found in geneid2symbol or synonyms2ID
SPMITTRNAASP.01 is not found in geneid2symbol or synonyms2ID
SPSNORNA.28 is not found in geneid2symbol or synonyms2ID
SPBTRNAILE.05 is not found in geneid2symbol or synonyms2ID
SPBTRNAILE.06 is not found in geneid2symbol or synonyms2ID
SPBTRNAVAL.05 is not found in geneid2symbol or synonyms2ID
SPBTRNATRP.02 is not found in geneid2symbol or synonyms2ID
SPCTRNAGLN.05 is not found in geneid2symbol or synonyms2ID
SPRRNA.13 is not found in geneid2symbol or synonyms2ID
SPMITTRNALYS.01 is not found in geneid2symbol or synonyms2ID
SPBTRNAALA.09 is not found in geneid2symbol or synonyms2ID
SPATRNASER.03 is not found in geneid2symbol or synonyms2ID
SPATRNALYS.03 is not found in geneid2symbol or synonyms2ID
SPSNORNA.08 is not found in geneid2symbol or synonyms2ID
SPBTRNAALA.08 is not found in geneid2symbol or synonyms2ID
SPCTRNALYS.10 is not found in geneid2symbol or synonyms2ID
SPMITTRNAMET.02 is not found in geneid2symbol or synonyms2ID
SPBTRNAGLU.06 is not found in geneid2symbol or synonyms2ID
SPBTRNAASN.03 is not found in geneid2symbol or synonyms2ID

### Concatenate evolutionary features

In [ ]:
coding_gene_evolutionary_features_df = pd.concat(
    [
        num_of_orthologs_with_japonicus.rename("japonicus_ortholog_count"),
        num_of_orthologs_with_cerevisiae.rename("cerevisiae_ortholog_count"),
        num_of_orthologs_with_human.rename("human_ortholog_count"),
        paralog_count,
        evolutionary_rate.set_index("gene_systematic_id")[["Rate"]].rename(columns={"Rate": "evolutionary_rate"}),
        phyloP_and_divergence.set_index("gene_systematic_id")[["mean.phylop", "diversity.S", "diversity.Pi", "diversity.Theta", "diversity.Tajima_D"]]
    ],
    join="outer",
    axis=1
)

coding_gene_evolutionary_features_df = coding_gene_evolutionary_features_df[coding_gene_evolutionary_features_df.index.isin(coding_genes)].copy()
coding_gene_evolutionary_features_df.info()

## 4.5 Network-level features

### GO term richness

In [24]:
dag, objanno, ns2assoc, gene2go, go2genes, slim_dag, ns2slim_assoc = load_ontology_data(
    OntologyDataConfig(
        ontology_obo=cfg.PomBase_resource_dir / "ontologies_and_associations" / "go-basic.obo",
        ontology_association_gaf=cfg.PomBase_resource_dir / "ontologies_and_associations" / "gene_ontology_annotation.gaf.tsv",
        slim_terms_table=[
            cfg.PomBase_resource_dir / "ontologies_and_associations" / "bp_go_slim_terms.tsv",
            cfg.PomBase_resource_dir / "ontologies_and_associations" / "mf_go_slim_terms.tsv",
            cfg.PomBase_resource_dir / "ontologies_and_associations" / "cc_go_slim_terms.tsv"
        ]
    ).load_data(),
    **{
        "relationships": {"is_a", "part_of"},
        "propagate_counts": True,
        "load_obsolete": False,
        "prt": None
    }
)

/data/c/yangyusheng_optimized/DIT_HAP_pipeline/resources/pombase_data/2025-10-01/ontologies_and_associations/go-basic.obo: fmt(1.2) rel(2025-10-10) 42,666 Terms; optional_attrs(def relationship)
HMS:0:00:01.439188  49,447 annotations READ: /data/c/yangyusheng_optimized/DIT_HAP_pipeline/resources/pombase_data/2025-10-01/ontologies_and_associations/gene_ontology_annotation.gaf.tsv

In [25]:
gene2gorichness = {}
for gene, go_terms in tqdm(gene2go.items(), desc="Calculating GO term richness"):
    gene2gorichness[gene] = len(set(go_terms))

go_richness = pd.DataFrame.from_dict(gene2gorichness, orient="index", columns=["GO_term_richness"])

Calculating GO term richness:   0%|          | 0/5262 [00:00<?, ?it/s]

Calculating GO term richness: 100%|██████████| 5262/5262 [00:00<00:00, 200188.92it/s]

### PPI degree and GI degree

In [26]:
biogrid_data = pd.read_csv("../../resources/BioGrid/BIOGRID-ORGANISM-Schizosaccharomyces_pombe_972h-5.0.251.tab3.txt", sep="\t")
PPI_and_GI = biogrid_data[['Systematic Name Interactor A',
       'Systematic Name Interactor B', 'Official Symbol Interactor A',
       'Official Symbol Interactor B', 'Experimental System Type']].drop_duplicates()

PPI = PPI_and_GI.query("`Experimental System Type` == 'physical'")
GI = PPI_and_GI.query("`Experimental System Type` == 'genetic'")

PPI_degrees = PPI.groupby('Systematic Name Interactor A').size().rename("PPI_degree")
GI_degrees = GI.groupby('Systematic Name Interactor A').size().rename("GI_degree")

/tmp/ipykernel_1962377/1673342136.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  biogrid_data = pd.read_csv("../../resources/BioGrid/BIOGRID-ORGANISM-Schizosaccharomyces_pombe_972h-5.0.251.tab3.txt", sep="\t")

### Concatenate network features

In [ ]:
coding_gene_network_features_df = pd.concat(
    [
        go_richness,
        PPI_degrees,
        GI_degrees
    ],
    join="outer",
    axis=1
)

coding_gene_network_features_df = coding_gene_network_features_df[coding_gene_network_features_df.index.isin(coding_genes)].copy()
coding_gene_network_features_df.info()

## 4.6 Phenotype-level features

### FYPO Essentiality

In [ ]:
FYPO_viability = pd.read_csv(cfg.PomBase_resource_dir / "Gene_metadata" / "gene_viability.tsv", sep="\t", header=None, names=["gene_systematic_id", "FYPOviability"]).set_index("gene_systematic_id")

### Deletion Library Results

In [ ]:
DeletionLibrary_essentiality = pd.read_excel("../../resources/Hayles_2013_OB_merged_categories_sysIDupdated.xlsx")[["Updated_Systematic_ID", "Gene dispensability. This study", "Category"]].set_index("Updated_Systematic_ID")

### Transposon insertion density

In [44]:
ins_PMID23893486 = pd.read_excel("../../resources/Literature/PMID23893486/genetics.113.152744-10.xls", sheet_name="TableS2")
ins_PMID23893486["gene_systematic_id"] = update_sysIDs(ins_PMID23893486["Gene name"].str.strip().apply(lambda row: sorted(row.split(" "))[0]).tolist(), cfg.gene_meta_file)
ins_PMID23893486.drop_duplicates(subset=["gene_systematic_id"], inplace=True)

/data/a/yangyusheng/miniforge3/envs/bioinformatics/lib/python3.12/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

Cwf15 is not found in geneid2symbol or synonyms2ID
SPAC212.10 is not found in geneid2symbol or synonyms2ID
SPAC212.09c is not found in geneid2symbol or synonyms2ID
SPAC212.07c is not found in geneid2symbol or synonyms2ID
SPAC212.05c is not found in geneid2symbol or synonyms2ID
SPAC977.13c is not found in geneid2symbol or synonyms2ID
SPAC1D4.07c is not found in geneid2symbol or synonyms2ID
SPAPB24D3.05c is not found in geneid2symbol or synonyms2ID
SPAC17A2.15 is not found in geneid2symbol or synonyms2ID
SPAC1F12.03c is not found in geneid2symbol or synonyms2ID
SPAC4H3.12c is not found in geneid2symbol or synonyms2ID
SPAC27E2.13 is not found in geneid2symbol or synonyms2ID
SPAC23D3.05c is not found in geneid2symbol or synonyms2ID
SPBC1348.11 is not found in geneid2symbol or synonyms2ID
SPBC1348.13 is not found in geneid2symbol or synonyms2ID
SPBPB21E7.06 is not found in geneid2symbol or synonyms2ID
SPBPB21E7.08 is not found in geneid2symbol or synonyms2ID
SPBPB10D8.03 is not found in geneid2symbol or synonyms2ID
SPBC1685.12c is not found in geneid2symbol or synonyms2ID
SPBC354.11c is not found in geneid2symbol or synonyms2ID
SPBC1706.02c is not found in geneid2symbol or synonyms2ID
SPBC31A8.02 is not found in geneid2symbol or synonyms2ID
SPBC18E5.15 is not found in geneid2symbol or synonyms2ID
SPBC11C11.12 is not found in geneid2symbol or synonyms2ID
SPBPB2B2.03c is not found in geneid2symbol or synonyms2ID
SPBPB2B2.04 is not found in geneid2symbol or synonyms2ID
SPBCPT2R1.05c is not found in geneid2symbol or synonyms2ID
SPBCPT2R1.09c is not found in geneid2symbol or synonyms2ID
SPBCPT2R1.06c is not found in geneid2symbol or synonyms2ID
SPBCPT2R1.07c is not found in geneid2symbol or synonyms2ID
SPBCPT2R1.10 is not found in geneid2symbol or synonyms2ID
SPCP20C8.03 is not found in geneid2symbol or synonyms2ID
SPCC548.02c is not found in geneid2symbol or synonyms2ID
SPCC553.05c is not found in geneid2symbol or synonyms2ID
SPCC306.10 is not found in geneid2symbol or synonyms2ID
SPCC18B5.02c is not found in geneid2symbol or synonyms2ID
SPCC132.05c is not found in geneid2symbol or synonyms2ID
SPCC622.21 is not found in geneid2symbol or synonyms2ID
SPCC622.05 is not found in geneid2symbol or synonyms2ID
SPCC188.05 is not found in geneid2symbol or synonyms2ID
SPCC188.10c is not found in geneid2symbol or synonyms2ID
SPCC663.07c is not found in geneid2symbol or synonyms2ID
SPCC417.04 is not found in geneid2symbol or synonyms2ID
SPCC1450.01c is not found in geneid2symbol or synonyms2ID
SPCC285.06c is not found in geneid2symbol or synonyms2ID
SPCC576.16c is not found in geneid2symbol or synonyms2ID
SPCC830.02 is not found in geneid2symbol or synonyms2ID
SPAC823.02 is updated to SPAC823.17
SPAC27D7.12 is updated to SPAC27D7.12c
B22918-2 is not found in geneid2symbol or synonyms2ID
DcpS is updated to SPBP4H10.20
SPBC8E4.02c is not found in geneid2symbol or synonyms2ID
B13958-2 is not found in geneid2symbol or synonyms2ID
Cul-4 is updated to SPAC3A11.08

### Concatenate phenotype features

In [ ]:
coding_gene_phenotype_features_df = pd.concat(
    [
        FYPO_viability,
        DeletionLibrary_essentiality,
        ins_PMID23893486.set_index("gene_systematic_id")[['Integration density, in-vivo (integrations/kb/million inserts)']]
    ],
    join="outer",
    axis=1
)

coding_gene_phenotype_features_df = coding_gene_phenotype_features_df[coding_gene_phenotype_features_df.index.isin(coding_genes)].copy()
coding_gene_phenotype_features_df.info()

## 4.7 Final feature matrix

In [91]:
pombe_features = pd.concat(
    [
        coding_gene_DNA_features_df.query("Primary_candidate == True").set_index("Gene_id"),
        coding_gene_RNA_features_df,
        coding_gene_protein_features_df,
        coding_gene_evolutionary_features_df,
        coding_gene_network_features_df,
        coding_gene_phenotype_features_df
    ],
    join="outer",
    axis=1  
).rename_axis("gene_systematic_id")

In [92]:
coding_gene_protein_features_df.to_csv(OUTPUT_DIR / "pombe_coding_gene_protein_features.tsv", sep="\t")